### ISSUE TITLE
Create private repository for credentials maintenance for edukai server

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/cleaningladylist.com#23]
- cleaningladylist.com
- getrector.org

## Todo

- [ ] create new private package
- [ ] add basic files
- [ ] figure out how to propagate it to the server on push, probably similar to deploy Github Action here

**Comment by JanMikes** [comment]
Other possibilities might be config servers/applications.

Such as hashicorp vault or SSM from AWS, im sure there might be more self-hosted or open source options.

It is question about what workflow is desired, because everything comes with pros and cons :-)
